version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./docker/deployment/Dockerfile
    command: gunicorn app.wsgi --bind=unix:/var/run/gunicorn/gunicorn.sock
    volumes:
      - .:/usr/src/app/
      - gunicorn:/run/gunicorn

  nginx:
    image: nginx:1.17.7
    ports:
      - 80:80
    volumes:
      - ./docker/deployment/nginx/conf.d:/etc/nginx/conf.d
      - gunicorn:/run/gunicorn
    depends_on:
      - django

volumes:
  gunicorn:
    driver: local
