# Generated by Django 3.1.6 on 2021-03-20 00:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'), max_length=50, verbose_name='作成したユーザー名')),
                ('question', models.CharField(help_text='問題タイトル', max_length=150, verbose_name='メモ問題')),
                ('image', models.ImageField(default='image/memo.jpg', upload_to='image/', verbose_name='アイコン')),
                ('text', models.TextField(help_text='問題内容', verbose_name='問題内容')),
                ('creat_time', models.DateField(default=datetime.datetime.today, verbose_name='作成日')),
                ('update_time', models.DateField(default=django.utils.timezone.now, verbose_name='復習日')),
                ('tag', models.CharField(blank=True, help_text='タグ', max_length=50, verbose_name='タグ')),
                ('counter', models.IntegerField(default=1, verbose_name='復習カウンター')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メモ',
                'verbose_name_plural': 'メモ',
            },
        ),
    ]
